name: CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Build
        run: npm install && npm run build
      - name: Commit build result
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update build